import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Footer from "./_components/footer";
import Header from "./_components/header";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={outfit.className}>
                <div className="md:px-20">
                    <Header />
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
